### ISSUE TITLE
not useful on herokuapp.com

### ISSUE THREAD

**Issue by jcomeauictx** [philipn/django-block-ip#1]
herokuapp.com uses NAT, so req.META['REMOTE_ADDR'] is an address in the 10/8 local network.

the environment variable HTTP_X_FORWARDED_FOR has the external address needed.

so, something like

    def get_ip(req):
        return req.META.get('HTTP_X_FORWARDED_FOR', req.META.get('REMOTE_ADDR'))

in block_ip.middleware ought to work in either environment. thanks!

**Comment by philipn** [comment]
I think you should use separate middleware for X-Forwarded-For, as it's a separate issue.  E.g. we use https://github.com/localwiki/localwiki/blob/hub/localwiki/utils/middleware.py#L12 and I think there are packages available.

**Comment by jcomeauictx** [comment]
OK, it's slightly more complicated that I thought, with the comma-space separator, but it would still be a good idea to add the slight bit of code necessary to make your software applicable to Heroku, IMO. but it's up to you. I'll just make my own middleware for now.

**Comment by mpachas** [comment]
@jcomeauictx may you share your middleware?
```def get_ip(req):
    return req.META.get('HTTP_X_FORWARDED_FOR', req.META.get('REMOTE_ADDR'))```
does this mod simply work on heroku?
Thanks

**Comment by jcomeauictx** [comment]
I found SetRemoteAddrFromForwardedFor after googling around for a bit. not sure now exactly where I got it, but it appears to be here also: https://pypi.python.org/pypi/commonware/0.2.4

**Comment by mpachas** [comment]
Thanks! I found django-banish, it has a config var
BANISH_USE_HTTP_X_FORWARDED_FOR = True
that allows you to get that real ip and block it.


2015-04-17 16:48 GMT+02:00 John Comeau <notifications@github.com>:
