### ISSUE TITLE
Check for HTTP_X_FORWARDED_FOR

### ISSUE THREAD

**Issue by groovecoder** [philipn/django-block-ip#2]
`get_ip` should check `req.META.get('HTTP_X_FORWARDED_FOR')`. [Some example code is in `django-banish`](https://github.com/yourabi/django-banish/blob/master/banish/middleware.py#L70-L74)

**Comment by philipn** [comment]
IMO, X-Forwarded-For should be handled in its own app.  There's a few edge cases (e.g. can accept multiple IPs), and the decision as to whether or not to accept the X-Forwarded-For address shouldn't be automatic (e.g. someone can spoof their IP if so) and touches lots of areas.

I'm cleaning up https://github.com/allo-/django-xforwardedfor-middleware, which should do the trick!
